language: python
dist: xenial
python:
  - 2.7
  - 3.6
sudo: false
matrix:
  include:
    - python: 3.6
      env: TOXENV=itresolver
    - python: 2.7
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=eslint
script:
  - tox
cache:
  directories:
    - ~/.cache/pip
    - ~/.nvm/nvm.sh
install:
  - pip install tox-travis
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install lts/carbon
  - nvm use lts/carbon
  - npm install -g bower gulp@^3.x
  - npm install
  - bower install
script:
  - tox
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
