version: '3.4'
services:
  http:
    image: nginx:1.16
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - "docs:/home/documents"
      - "./docker/nginx/conf.d/general-configuration.conf:/etc/nginx/conf.d/general-configuration.conf"
      - "./docker/nginx/snippets/:/etc/nginx/snippets/"
      - "./docker/nginx/sites-available/readthedocs-main.conf:/etc/nginx/conf.d/default.conf"

  web:
    container_name: italia_docs_italia_it_web
    build:
      context: .
      target: docs_italia_it_web
    image: italia/docs_italia_it:latest
    depends_on:
      - db
      - es
      - redis
    ports:
      - "8001:8001"
    command: docker/gunicorn.sh collect ${GUNICORN_WEB_OPS} -w ${GUNICORN_WEB_WORKERS} -b 0.0.0.0:8001
    volumes:
      - ".:/app:rw"
      - "docs:/home/documents"
    env_file:
      - .dockerenv
      - .secrets

  api:
    container_name: italia_docs_italia_it_api
    image: italia/docs_italia_it:latest
    depends_on:
      - web
    ports:
      - "8002:8002"
    command: docker/gunicorn.sh ${GUNICORN_WEB_OPS} -w ${GUNICORN_WEB_WORKERS} -b 0.0.0.0:8002
    volumes:
      - ".:/app:rw"
      - "docs:/home/documents"
    env_file:
      - .dockerenv
      - .secrets

  celery-web:
    container_name: italia_docs_italia_it_celery_web
    image: italia/docs_italia_it:latest
    depends_on:
      - web
    command: docker/celery.sh -A ${CELERY_APP} ${CELERY_WEB_OPTS} -l ${CELERY_LOGLEVEL}
    volumes:
      - ".:/app:rw"
      - "docs:/home/documents"
    env_file:
      - .dockerenv
      - .secrets

  celery-docs:
    container_name: italia_docs_italia_it_celery_docs
    image: italia/docs_italia_it:latest
    depends_on:
      - web
    command: docker/celery.sh -A ${CELERY_APP} ${CELERY_DOCS_OPTS} -l ${CELERY_LOGLEVEL}
    volumes:
      - docs:/home/documents
    env_file:
      - .dockerenv
      - .secrets

  celery-build:
    container_name: italia_docs_italia_it_celery_build
    build:
      context: .
      target: docs_italia_it_build
    image: italia/docs_italia_it_build:latest
    depends_on:
      - web
    command: docker/celery.sh -A ${CELERY_APP} ${CELERY_BUILD_OPTS} -l ${CELERY_LOGLEVEL}
    volumes:
      - ".:/app:rw"
      - "docs:/home/documents"
      -  "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .dockerenv
      - .secrets

  db:
    image: postgres:10
    volumes:
      - dbdata

  es:
    build:
      context: docker/elasticsearch
    volumes:
      - esdata

  redis:
    image: redis

volumes:
  docs:
  dbdata:
  esdata:
