version: '3.4'
services:
  py36:
    container_name: italia_docs_italia_it_test
    build:
      context: .
      target: docs_italia_it_test
    image: italia/docs_italia_it_test:latest
    depends_on:
      - db
    environment:
      - TRAVIS_DOCSITALIA_DOCKER=1
    command: tox -e itresolver -- $PYTEST_ARGS
    volumes:
      - ".:/app:rw"
      - ".tox:/app/.tox"
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=docs
      - POSTGRES_USER=docs
      - POSTGRES_DB=test_rtd

volumes:
  tox:
